#include "matgen/io/mtx_writer.h"

#include <stdio.h>

#include "matgen/util/log.h"

// =============================================================================
// COO Writer
// =============================================================================

matgen_error_t matgen_mtx_write_coo(const char* filename,
                                    const matgen_coo_matrix_t* matrix) {
  if (!filename || !matrix) {
    MATGEN_LOG_ERROR("NULL pointer argument");
    return MATGEN_ERROR_INVALID_ARGUMENT;
  }

  if (!matgen_coo_validate(matrix)) {
    MATGEN_LOG_ERROR("Invalid COO matrix");
    return MATGEN_ERROR_INVALID_ARGUMENT;
  }

  MATGEN_LOG_DEBUG("Writing COO matrix to %s (%llu x %llu, nnz=%zu)", filename,
                   (unsigned long long)matrix->rows,
                   (unsigned long long)matrix->cols, matrix->nnz);

  FILE* f = fopen(filename, "w");
  if (!f) {
    MATGEN_LOG_ERROR("Failed to open file for writing: %s", filename);
    return MATGEN_ERROR_IO;
  }

  // Write header
  fprintf(f, "%%%%MatrixMarket matrix coordinate real general\n");
  fprintf(f, "%% Generated by MatGen\n");

  // Write dimensions
  fprintf(f, "%llu %llu %zu\n", (unsigned long long)matrix->rows,
          (unsigned long long)matrix->cols, matrix->nnz);

  // Write entries (convert to 1-based indexing)
  for (matgen_size_t i = 0; i < matrix->nnz; i++) {
    fprintf(f, "%llu %llu %.16g\n",
            (unsigned long long)(matrix->row_indices[i] + 1),
            (unsigned long long)(matrix->col_indices[i] + 1),
            matrix->values[i]);
  }

  fclose(f);

  MATGEN_LOG_DEBUG("Successfully wrote MTX file");

  return MATGEN_SUCCESS;
}

// =============================================================================
// CSR Writer
// =============================================================================

matgen_error_t matgen_mtx_write_csr(const char* filename,
                                    const matgen_csr_matrix_t* matrix) {
  if (!filename || !matrix) {
    MATGEN_LOG_ERROR("NULL pointer argument");
    return MATGEN_ERROR_INVALID_ARGUMENT;
  }

  if (!matgen_csr_validate(matrix)) {
    MATGEN_LOG_ERROR("Invalid CSR matrix");
    return MATGEN_ERROR_INVALID_ARGUMENT;
  }

  MATGEN_LOG_DEBUG("Writing CSR matrix to %s (%llu x %llu, nnz=%zu)", filename,
                   (unsigned long long)matrix->rows,
                   (unsigned long long)matrix->cols, matrix->nnz);

  FILE* f = fopen(filename, "w");
  if (!f) {
    MATGEN_LOG_ERROR("Failed to open file for writing: %s", filename);
    return MATGEN_ERROR_IO;
  }

  // Write header
  fprintf(f, "%%%%MatrixMarket matrix coordinate real general\n");
  fprintf(f, "%% Generated by MatGen\n");

  // Write dimensions
  fprintf(f, "%llu %llu %zu\n", (unsigned long long)matrix->rows,
          (unsigned long long)matrix->cols, matrix->nnz);

  // Write entries by iterating through CSR structure
  // Convert to 1-based indexing
  for (matgen_index_t row = 0; row < matrix->rows; row++) {
    matgen_size_t row_start = matrix->row_ptr[row];
    matgen_size_t row_end = matrix->row_ptr[row + 1];

    for (matgen_size_t j = row_start; j < row_end; j++) {
      fprintf(f, "%llu %llu %.16g\n", (unsigned long long)(row + 1),
              (unsigned long long)(matrix->col_indices[j] + 1),
              matrix->values[j]);
    }
  }

  fclose(f);

  MATGEN_LOG_DEBUG("Successfully wrote MTX file");

  return MATGEN_SUCCESS;
}
